name: Build iOS IPA

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Create dummy file
        run: |
          mkdir -p build
          echo "test content" > build/test.txt
          ls -la build/
          
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-file
          path: build/test.txt