name: Build iOS IPA

on:
  workflow_dispatch:
    inputs:
      download_url:
        description: 'URL để tải xuống dự án Xcode'
        required: true
        default: 'https://drive.google.com/uc?export=download&id=1RKSI64zoHHgwLxfF2DMiOEJMyiEoGMSm'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Tải xuống dự án Xcode
        run: |
          curl -L "${{ github.event.inputs.download_url }}" -o project.zip
          unzip project.zip
          ls -la
          
      - name: Build IPA
        run: |
          # Tìm thư mục xcodeproj
          XCODEPROJ_PATH=$(find . -name "*.xcodeproj" -type d | head -n 1)
          if [ -z "$XCODEPROJ_PATH" ]; then
            echo "Không tìm thấy file xcodeproj!"
            exit 1
          fi
          
          echo "Đang build project: $XCODEPROJ_PATH"
          cd $(dirname "$XCODEPROJ_PATH")
          
          PROJECT_NAME=$(basename "$XCODEPROJ_PATH" .xcodeproj)
          echo "Tên project: $PROJECT_NAME"
          
          # Build không ký
          xcodebuild -project "$PROJECT_NAME.xcodeproj" -scheme "$PROJECT_NAME" -configuration Release -arch arm64 -sdk iphoneos CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          
          # Tạo IPA
          mkdir -p Payload
          cp -R "build/Release-iphoneos/$PROJECT_NAME.app" Payload/
          zip -r "$PROJECT_NAME.ipa" Payload
          
      - name: Upload IPA
        uses: actions/upload-artifact@v2
        with:
          name: iOS-App
          path: "**/*.ipa"